#!/bin/bash
OLD_HOME=$HOME
echo "Bower & Gulp"
export HOME=$OPENSHIFT_REPO_DIR
if [ -f "${OPENSHIFT_REPO_DIR}"/bower.json ]; then
 (cd "${OPENSHIFT_REPO_DIR}"; node_modules/.bin/bower install)
fi
if [ -f "${OPENSHIFT_REPO_DIR}"/gulpfile.js ]; then
 (cd "${OPENSHIFT_REPO_DIR}"; node_modules/.bin/gulp build)
fi
export HOME=$OLD_HOME